const places={
 'Mi ubicación':[10.491,-66.902],'Centro de Caracas':[10.506,-66.914],'Plaza Venezuela':[10.494,-66.879],Chacao:[10.486,-66.853],Altamira:[10.497,-66.849],'Sabana Grande':[10.493,-66.873]
};
const map=L.map('map').setView(places['Mi ubicación'],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let originMarker=null,destMarker=null,routeLayers=[],selectedRouteIndex=0,currentRoutes=[],gtfs=null;
function clearRouteLayers(){routeLayers.forEach(x=>map.removeLayer(x));routeLayers=[]}
function clearMap(){clearRouteLayers();if(originMarker)map.removeLayer(originMarker);if(destMarker)map.removeLayer(destMarker);originMarker=destMarker=null}
function setMarkers(o,d){clearMap();originMarker=L.marker(o).addTo(map).bindPopup('Origen');destMarker=L.marker(d).addTo(map).bindPopup('Destino')}
function geometryLayer(coords,opts={}){return L.polyline(coords,{weight:opts.weight||6,opacity:opts.opacity??.9,dashArray:opts.dashArray||null})}
async function roadRoute(a,b){const url=`https://router.project-osrm.org/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?alternatives=3&overview=full&geometries=geojson`;const r=await fetch(url);if(!r.ok)throw Error('OSRM');const j=await r.json();if(j.code!=='Ok')throw Error('OSRM');return j.routes.map((x,i)=>({name:i===0?'Ruta NEXO Express':`Ruta alternativa ${i+1}`,kind:'Calles reales · OSRM',mode:'road',time:Math.max(1,Math.round(x.duration/60)),walk:i===0?5:7+i,cost:(.8+x.distance/1000*.16).toFixed(2),distance:(x.distance/1000).toFixed(1),geometry:x.geometry.coordinates.map(p=>[p[1],p[0]])}));}
function nearestStop(p){const stops=(gtfs?.stops||[]).map(s=>({name:s.name,coord:[s.lat,s.lon],id:s.id,d:Math.hypot(s.lat-p[0],s.lon-p[1])}));return stops.sort((a,b)=>a.d-b.d)[0]}
async function segment(a,b){try{const u=`https://router.project-osrm.org/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?overview=full&geometries=geojson`;const j=await (await fetch(u)).json();return j.routes?.[0]?.geometry?.coordinates?.map(p=>[p[1],p[0]])||[a,b]}catch{return[a,b]}}
function routeStops(route){return route.stops.map(id=>gtfs.stops.find(s=>s.id===id)).filter(Boolean)}
async function buildTransitOption(route,a,b){const stops=routeStops(route);if(stops.length<2)return null;const os=nearestStop(a),ds=nearestStop(b);const first=stops.reduce((best,s)=>Math.hypot(s.lat-a[0],s.lon-a[1])<Math.hypot(best.lat-a[0],best.lon-a[1])?s:best,stops[0]);const last=stops.reduce((best,s)=>Math.hypot(s.lat-b[0],s.lon-b[1])<Math.hypot(best.lat-b[0],best.lon-b[1])?s:best,stops[stops.length-1]);const [walkIn,walkOut]=await Promise.all([segment(a,[first.lat,first.lon]),segment([last.lat,last.lon],b)]);const transit=route.shape;const geometry=[...walkIn,...transit,...walkOut];const walk=Math.max(2,Math.round((Math.hypot(first.lat-a[0],first.lon-a[1])*111)*60/4)+Math.round((Math.hypot(last.lat-b[0],last.lon-b[1])*111)*60/4));return {name:`${route.long_name} · ${first.name} → ${last.name}`,kind:`Transporte público · GTFS ${route.id}`,mode:'transit',time:Math.max(12,walk+Math.round(transit.length*4)+8),walk,cost:route.fare.toFixed(2),distance:'—',geometry,segments:[{mode:'walk',coords:walkIn},{mode:'transit',coords:transit},{mode:'walk',coords:walkOut}],note:`Datos de demostración con estructura GTFS. Línea ${route.short_name}.`}}
async function transitRoutes(a,b){if(!gtfs?.routes?.length)throw Error('GTFS');const opts=[];for(const r of gtfs.routes.slice(0,4)){const x=await buildTransitOption(r,a,b);if(x)opts.push(x)}return opts.sort((x,y)=>x.time-y.time)}
function showRouteOnMap(index){const r=currentRoutes[index];if(!r)return;clearRouteLayers();if(r.segments){r.segments.forEach(s=>{const style=s.mode==='transit'?{weight:8,opacity:.95}:{weight:5,opacity:.85,dashArray:'7 8'};const layer=geometryLayer(s.coords,style);layer.addTo(map);routeLayers.push(layer)})}else if(r.geometry?.length){const layer=geometryLayer(r.geometry,{weight:7});layer.addTo(map);routeLayers.push(layer)}document.querySelectorAll('.route').forEach((el,i)=>{el.classList.toggle('selected',i===index);const b=el.querySelector('.badge');if(b)b.textContent=i===index?'SELECCIONADA':'VER EN MAPA'});selectedRouteIndex=index;document.getElementById('mapStatus').textContent=`Ruta seleccionada: ${r.name} · ${r.time} min · $${r.cost}`;toast(`Mapa actualizado: ${r.name}`)}
function renderRoutes(routes){currentRoutes=routes;const box=document.getElementById('routes');box.innerHTML='';if(!routes.length){box.innerHTML='<div class="empty">No encontramos rutas disponibles.</div>';return}routes.forEach((r,i)=>{const el=document.createElement('article');el.className='route'+(i===0?' selected':'');el.innerHTML=`<div class="top"><div><h3>${r.name}</h3><p>${r.time} min · ${r.walk} min caminando · $${r.cost}</p><p>${r.kind}${r.distance!=='—'?' · '+r.distance+' km':''}</p>${r.note?`<p>${r.note}</p>`:''}</div><span class="badge">${i===0?'SELECCIONADA':'VER EN MAPA'}</span></div><button>Ver esta ruta en el mapa</button>`;el.addEventListener('click',()=>showRouteOnMap(i));box.appendChild(el)});showRouteOnMap(0)}
async function loadGTFS(){try{const r=await fetch('./gtfs-demo.json',{cache:'no-store'});if(!r.ok)throw Error('GTFS');gtfs=await r.json();document.getElementById('mapStatus').textContent=`Datos de transporte cargados · ${gtfs.routes.length} líneas demo`;return true}catch{document.getElementById('mapStatus').textContent='Transporte público no disponible ahora.';return false}}
async function searchMultimodal(){const on=document.getElementById('origin').value.trim()||'Mi ubicación',dn=document.getElementById('destination').value.trim();const o=places[on]||places['Mi ubicación'],d=places[dn];if(!d){toast('Escribe o selecciona un destino disponible.');return}setMarkers(o,d);document.getElementById('mapStatus').textContent='Calculando rutas por calles y transporte…';try{const road=await roadRoute(o,d);const transit=await transitRoutes(o,d);renderRoutes([...road,...transit]);}catch(e){try{const road=await roadRoute(o,d);renderRoutes(road)}catch{document.getElementById('mapStatus').textContent='No se pudo calcular la ruta ahora.';toast('No se pudo calcular la ruta. Intenta de nuevo.')}}}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';clearTimeout(window._t);window._t=setTimeout(()=>x.style.display='none',1800)}
document.getElementById('searchBtn').addEventListener('click',searchMultimodal);document.querySelectorAll('[data-dest]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('destination').value=b.dataset.dest;searchMultimodal()}));
document.getElementById('locateBtn').addEventListener('click',()=>{if(!navigator.geolocation){toast('La ubicación no está disponible en este navegador');return}navigator.geolocation.getCurrentPosition(p=>{const c=[p.coords.latitude,p.coords.longitude];places['Mi ubicación']=c;document.getElementById('origin').value='Mi ubicación';map.setView(c,15);toast('Ubicación actualizada')},()=>toast('No se pudo obtener tu ubicación'))});
loadGTFS();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
