const places={
 'Mi ubicación':[10.491,-66.902],'Centro de Caracas':[10.506,-66.914],'Plaza Venezuela':[10.494,-66.879],Chacao:[10.486,-66.853],Altamira:[10.497,-66.849],'Sabana Grande':[10.493,-66.873]
};
const map=L.map('map').setView(places['Mi ubicación'],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let originMarker=null,destMarker=null,routeLayers=[],selectedRouteIndex=0,currentRoutes=[];
function clearRouteLayers(){routeLayers.forEach(x=>map.removeLayer(x));routeLayers=[]}
function clearMap(){clearRouteLayers();if(originMarker)map.removeLayer(originMarker);if(destMarker)map.removeLayer(destMarker);originMarker=destMarker=null}
function setMarkers(o,d){clearMap();originMarker=L.marker(o).addTo(map).bindPopup('Origen');destMarker=L.marker(d).addTo(map).bindPopup('Destino')}
function geometryLayer(coords,opts={}){return L.polyline(coords,{weight:opts.weight||6,opacity:.9,dashArray:opts.dashArray||null})}
async function roadRoute(a,b){const url=`https://router.project-osrm.org/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?alternatives=3&overview=full&geometries=geojson`;const r=await fetch(url);if(!r.ok)throw Error('OSRM');const j=await r.json();if(j.code!=='Ok')throw Error('OSRM');return j.routes.map((x,i)=>({name:i===0?'Ruta NEXO Express':`Ruta alternativa ${i+1}`,kind:'Calles reales · OSRM',time:Math.max(1,Math.round(x.duration/60)),walk:i===0?5:7+i,cost:(.8+x.distance/1000*.16).toFixed(2),distance:(x.distance/1000).toFixed(1),geometry:x.geometry.coordinates.map(p=>[p[1],p[0]])}));}
function nearestStop(p){const stops=Object.entries(places).filter(([n])=>n!=='Mi ubicación').map(([name,coord])=>({name,coord,d:Math.hypot(coord[0]-p[0],coord[1]-p[1])}));return stops.sort((a,b)=>a.d-b.d)[0]}
async function segment(a,b){try{const u=`https://router.project-osrm.org/route/v1/driving/${a[1]},${a[0]};${b[1]},${b[0]}?overview=full&geometries=geojson`;const j=await (await fetch(u)).json();return j.routes?.[0]?.geometry?.coordinates?.map(p=>[p[1],p[0]])||[a,b]}catch{return[a,b]}}
async function transitRoute(a,b){const os=nearestStop(a),ds=nearestStop(b);const [s1,s2,s3]=await Promise.all([segment(a,os.coord),segment(os.coord,ds.coord),segment(ds.coord,b)]);const g=[...s1,...s2.slice(1),...s3.slice(1)];return [{name:'Combinada · caminar + bus',kind:'Transporte público · DEMO',time:31,walk:6,cost:'1.10',distance:'—',geometry:g,note:`Camina a ${os.name}, bus y conexión a ${ds.name}.`},{name:'Bus con menos caminata',kind:'Transporte público · DEMO',time:35,walk:2,cost:'1.50',distance:'—',geometry:g,note:'Opción demostrativa con menos caminata.'},{name:'Ruta económica',kind:'Transporte público · DEMO',time:42,walk:8,cost:'0.75',distance:'—',geometry:g,note:'Opción demostrativa de menor costo.'}]} 
function showRouteOnMap(index){const r=currentRoutes[index];if(!r)return;clearRouteLayers();if(r.geometry?.length){const layer=geometryLayer(r.geometry,{weight:7});layer.addTo(map);routeLayers.push(layer);map.fitBounds(layer.getBounds(),{padding:[35,35]})}document.querySelectorAll('.route').forEach((el,i)=>el.classList.toggle('selected',i===index));selectedRouteIndex=index;document.getElementById('mapStatus').textContent=`Ruta seleccionada: ${r.name} · ${r.time} min · $${r.cost}`;toast(`Mapa actualizado: ${r.name}`)}
function renderRoutes(routes){currentRoutes=routes;const box=document.getElementById('routes');box.innerHTML='';routes.forEach((r,i)=>{const el=document.createElement('article');el.className='route'+(i===0?' selected':'');el.innerHTML=`<div class="top"><div><h3>${r.name}</h3><p>${r.time} min · ${r.walk} min caminando · $${r.cost}</p><p>${r.kind}${r.distance!=='—'?' · '+r.distance+' km':''}</p>${r.note?`<p>${r.note}</p>`:''}</div><span class="badge">${i===0?'SELECCIONADA':'VER EN MAPA'}</span></div><button>Ver esta ruta en el mapa</button>`;el.addEventListener('click',()=>showRouteOnMap(i));box.appendChild(el)});if(routes.length)showRouteOnMap(0)}
async function searchMultimodal(){const on=document.getElementById('origin').value.trim()||'Mi ubicación',dn=document.getElementById('destination').value.trim();const o=places[on]||places['Mi ubicación'],d=places[dn];if(!d){toast('Escribe o selecciona un destino disponible.');return}document.getElementById('mapStatus').textContent='Calculando rutas por calles reales…';try{const road=await roadRoute(o,d);const transit=await transitRoute(o,d);renderRoutes([...road,...transit]);}catch(e){try{const transit=await transitRoute(o,d);renderRoutes(transit)}catch{document.getElementById('mapStatus').textContent='No se pudo calcular la ruta ahora.';toast('No se pudo calcular la ruta. Intenta de nuevo.')}}}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';clearTimeout(window._t);window._t=setTimeout(()=>x.style.display='none',1800)}
document.getElementById('searchBtn').addEventListener('click',searchMultimodal);document.querySelectorAll('[data-dest]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('destination').value=b.dataset.dest;searchMultimodal()}));
document.getElementById('locateBtn').addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>{const c=[p.coords.latitude,p.coords.longitude];places['Mi ubicación']=c;document.getElementById('origin').value='Mi ubicación';map.setView(c,15);toast('Ubicación actualizada') ,()=>toast('No se pudo obtener tu ubicación')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
